; Gerado automaticamente pelo AHK Hub (AutoHotkey v2)
#Requires AutoHotkey v2.0
#SingleInstance Force
SendMode "Input"

; ==== Remapeamentos ====

; === AHK_HUB_STATE_BEGIN ===
; eyJyZW1hcHBpbmdzIjpbXSwiZnVuY3Rpb25zIjpbeyJpZCI6MSwibmFtZSI6InRlc3QiLCJkZXNjcmlwdGlvbiI6IiIsImNvZGUiOiJ0ZXN0KCkge1xuICAgIHN5c3RlbV9jb250cm9sbGVyX2Z1bmN0aW9uX3JvbGFyKFwiVXBcIiwgNSlcbiAgICBzeXN0ZW1fY29udHJvbGxlcl9mdW5jdGlvbl9tb3Zlcl9tb3VzZSg0OTAsIDQ0MSwgMClcbiAgICBmIDo9IFwiMVwiXG4gICAgZiA6PSBcImhcIlxufSIsInBhcmFtcyI6W10sImJ1aWxkZXIiOnsibW9kZSI6InN0ZXBzIiwic3RlcHMiOlt7ImtpbmQiOiJidWlsdGluIiwiZnVuY3Rpb25JZCI6InNjcm9sbCIsImFyZ3MiOnsiZGlyZWN0aW9uIjp7ImtpbmQiOiJsaXRlcmFsIiwidmFsdWUiOiJVcCJ9LCJhbW91bnQiOnsia2luZCI6ImxpdGVyYWwiLCJ2YWx1ZSI6NX19fSx7ImtpbmQiOiJidWlsdGluIiwiZnVuY3Rpb25JZCI6Im1vdmVNb3VzZSIsImFyZ3MiOnsieCI6eyJraW5kIjoibGl0ZXJhbCIsInZhbHVlIjo0OTB9LCJ5Ijp7ImtpbmQiOiJsaXRlcmFsIiwidmFsdWUiOjQ0MX0sImZ1bGxTY3JlZW4iOnsia2luZCI6ImxpdGVyYWwiLCJ2YWx1ZSI6ZmFsc2V9fX0seyJraW5kIjoidmFyaWFibGVBY3Rpb24iLCJhY3Rpb24iOiJjcmVhdGUiLCJ0YXJnZXROYW1lIjoiZiIsInZhclR5cGUiOiJ0ZXh0IiwiaW5pdGlhbFZhbHVlIjoiMSIsInNjb3BlIjoibG9jYWwifSx7ImtpbmQiOiJ2YXJpYWJsZUFjdGlvbiIsImFjdGlvbiI6InNldCIsInRhcmdldE5hbWUiOiJmIiwidmFsdWUiOnsia2luZCI6ImxpdGVyYWwiLCJ2YWx1ZSI6ImgifX1dfX1dLCJ2YXJpYWJsZXMiOltdfQ==
; === AHK_HUB_STATE_END ===