/**
 * English strings only. Portuguese needs no dictionary — every call site's
 * fallback argument IS the Portuguese copy, so pt is "free" and always complete.
 * Missing English keys simply fall back to the Portuguese text.
 */
export const en: Record<string, string> = {
  // common
  "common.yes": "Yes",
  "common.no": "No",
  "common.select": "Select",
  "common.optionalSuffix": " (optional)",

  // dashboard / topbar
  "dashboard.save": "Save",
  "dashboard.saveTooltip":
    "Saves to the current file (or asks where, if there isn't one yet) and reloads the script — useful while testing",
  "dashboard.saveAs": "Save As",
  "dashboard.saveAsTooltip": "Asks for a new location to save and reloads the script",
  "dashboard.loadTooltip": "Loads a .ahk script generated by this app",
  "dashboard.tabRemappings": "Remappings",
  "dashboard.tabFunctions": "Functions",
  "dashboard.tabVariables": "Global variables",
  "dashboard.desktopOnlySave": "Saving is only available in the desktop app.",
  "dashboard.desktopOnlyLoad": "Loading is only available in the desktop app.",
  "dashboard.savedAndReloaded": "Script saved and reloaded at {{path}}",
  "dashboard.savedButRunError": "Saved, but there was an error running it: {{error}}",
  "dashboard.saveError": "Error saving: {{error}}",
  "dashboard.loadError": "Error loading: {{error}}",
  "dashboard.loadedFrom": "Script loaded from {{path}}",
  "dashboard.outOfSpecExtension":
    "File doesn't match the expected format, can't load it (must be a .ahk file).",
  "dashboard.outOfSpec": "File doesn't match the expected format, can't load it: {{error}}.",
  "dashboard.untitledTitle": "new script.ahk*",

  // variables & conditions section
  "variablesSection.variablesTitle": "Global variables",
  "variablesSection.addVariable": "Add new",
  "variablesSection.emptyVariables": "No variables yet.",
  "variablesSection.initialValue": "initial value",
  "variablesSection.hint":
    "You can also create a global variable straight from inside a function, on the Functions tab — it shows up here too.",
  "variablesSection.newVariable": "New variable",
  "variablesSection.editVariable": "Edit variable",
  "variablesSection.nameLabel": "Name",
  "variablesSection.namePlaceholder": "e.g. counter",
  "variablesSection.typeLabel": "Type",
  "variablesSection.initialValueLabel": "Initial value",
  "variablesSection.trueLabel": "True",

  // remappings section
  "remappings.sectionTitle": "Remappings",
  "remappings.addRemapping": "Add new",
  "remappings.newTitle": "New remapping",
  "remappings.editTitle": "Edit remapping",
  "remappings.sourceKey": "Source key",
  "remappings.destFunction": "Destination function",
  "remappings.triggerLabel": "Fire",
  "remappings.triggerDown": "On press",
  "remappings.triggerUp": "On release",
  "remappings.triggerFull": "Default",
  "remappings.triggerDownHint": "Runs once on press, and only fires again after the key is released.",
  "remappings.triggerFullHint": "Default remap — fires on press and can repeat if the key is held down.",
  "remappings.selectFunction": "Select a function",
  "remappings.groupCustom": "Custom",
  "remappings.cancel": "Cancel",
  "remappings.save": "Save",
  "remappings.add": "Add",
  "remappings.emptyList": "No remappings yet.",
  "remappings.edit": "Edit",
  "remappings.remove": "Remove",
  "remappings.params": "Parameters",

  // functions section
  "functionsSection.defaultTitle": "Default functions",
  "functionsSection.customTitle": "Custom functions",
  "functionsSection.badgeDefault": "Default",
  "functionsSection.badgeInternal": "Internal use",
  "functionsSection.badgeInternalTooltip":
    "Can't be used directly in a remapping — only makes sense as a step inside another function",
  "functionsSection.descriptionLabel": "Description",
  "functionsSection.descriptionPlaceholder": "What this function does",
  "functionsSection.add": "Add",
  "functionsSection.save": "Save",
  "functionsSection.emptyCustomList": "No custom functions yet.",
  "functionsSection.edit": "Edit",
  "functionsSection.remove": "Remove",
  "functionsSection.addFunction": "Add new",
  "functionsSection.newTitle": "New function",
  "functionsSection.editTitle": "Edit function",
  "functionsSection.codeWarning":
    "Write only one function's code here. Anything beyond that might make the script behave unexpectedly or throw an error — nothing too serious, but it's on you, so it's worth double-checking before saving.",
  "functionsSection.chooseTypeHint": "Choose how you want to create the function:",
  "functionsSection.modeCode": "Write pure AHK code",
  "functionsSection.codeLabel": "AHK code",
  "functionsSection.detectedName": "Detected name: {{name}}",
  "functionsSection.noNameDetected":
    "Write the function header (e.g. FunctionName() { ... }) so the name can be detected.",
  "functionsSection.modeSteps": "Build from a sequence of commands",
  "functionsSection.nameLabel": "Function name",
  "functionsSection.namePlaceholder": "e.g. OpenNotes",
  "functionsSection.invalidName": "Invalid name: use only letters, numbers and _, and don't start with a number.",
  "functionsSection.stepsHint":
    "Build the function with a header (name and parameters) and a body (steps in the order they should happen). When calling another function in a step, its parameters can come from a compatible header parameter or a fixed value.",
  "functionsSection.headerSectionTitle": "Header",
  "functionsSection.bodySectionTitle": "Body",
  "functionsSection.headerParamsTitle": "Function parameters",
  "functionsSection.emptyHeaderParams": "No parameters added yet.",
  "functionsSection.paramNamePlaceholder": "e.g. text",
  "functionsSection.paramTypeText": "Text",
  "functionsSection.paramTypeNumber": "Number",
  "functionsSection.paramTypeBoolean": "Boolean",
  "functionsSection.paramTypeSelect": "Selection",
  "functionsSection.paramTypeCoordinate": "Screen coordinate",
  "functionsSection.paramTypeKeyCombo": "Key",
  "functionsSection.paramOptionsLabel": "Selection options",
  "functionsSection.paramOptionPlaceholder": "e.g. Fast",
  "functionsSection.addParamOption": "Add option",
  "functionsSection.addParam": "Add parameter",
  "functionsSection.emptySteps": "No steps added yet.",
  "functionsSection.groupCustom": "Custom",
  "functionsSection.groupVariableActions": "Variables",
  "functionsSection.varActionSet": "Set value",
  "functionsSection.varActionIncrement": "Increment/decrement",
  "functionsSection.varActionToggle": "Toggle",
  "functionsSection.varActionCreate": "Create variable",
  "functionsSection.varActionPromptInput": "Ask user for text (InputBox)",
  "functionsSection.varActionPromptInputDescription":
    "Opens a box asking for text and stores what was typed into a variable.",
  "functionsSection.varActionPromptTitleLabel": "Box title",
  "functionsSection.varActionPromptTitlePlaceholder": "e.g. File name",
  "functionsSection.varActionPromptTextLabel": "Prompt text",
  "functionsSection.varActionPromptTextPlaceholder": "e.g. Type the file name:",
  "functionsSection.varActionTargetLabel": "Variable",
  "functionsSection.varActionNewNameLabel": "New variable name",
  "functionsSection.varActionValueLabel": "New value",
  "functionsSection.varActionUsingSource": 'Using "{{name}}"',
  "functionsSection.varActionAmountLabel": "Amount (can be negative)",
  "functionsSection.varActionScopeLabel": "Scope",
  "functionsSection.varActionScopeLocal": "Local",
  "functionsSection.varActionScopeGlobal": "Global",
  "functionsSection.varActionScopeGlobalHint": "It'll also show up on the Global variables tab.",
  "functionsSection.varActionCreateTag": "create",
  "functionsSection.varActionCreateLocalTag": "local",
  "functionsSection.varActionCreateGlobalTag": "global",
  "functionsSection.noVariablesAvailable": "No variables available — create one first.",
  "functionsSection.selectVariablePlaceholder": "Select a variable",
  "functionsSection.newStepTitle": "New step",
  "functionsSection.editStepTitle": "Edit step",
  "functionsSection.selectStepFunction": "Select a function",
  "functionsSection.addStep": "Add step",
  "functionsSection.cancel": "Cancel",

  // command recording
  "functionsSection.startRecording": "Record commands",
  "functionsSection.recordDesktopOnly": "Recording commands is only available in the desktop app.",
  "functionsSection.recordingTitle": "Recording commands...",
  "functionsSection.recordingPausedTitle": "Recording paused",
  "functionsSection.startCapturing": "Start",
  "functionsSection.pauseRecording": "Pause recording",
  "functionsSection.resumeRecording": "Resume recording",
  "functionsSection.recordClickFullScreen": "Consider clicks relative to the whole screen (otherwise, to the clicked window)",
  "functionsSection.recordInsertWaits": "Insert waits between steps (real time between actions)",
  "functionsSection.recordConvertDrag": "Convert held clicks into a drag",
  "functionsSection.recordTimeKeys": "Time held keys (real time held)",
  "functionsSection.recordingEmpty": "No commands recorded yet — use the mouse/keyboard outside the app.",
  "functionsSection.discardRecording": "Discard",
  "functionsSection.addRecordedSteps": "Add steps",

  // flow control (Loop / Conditional) steps
  "functionsSection.flowLoopLabel": "Loop",
  "functionsSection.flowLoopDescription": "Repeats the following steps while a condition is true.",
  "functionsSection.flowConditionalLabel": "Conditional",
  "functionsSection.flowConditionalDescription": "Runs the following steps only if a condition is true.",
  "functionsSection.flowLoopSummary": "Loop while {{condition}}",
  "functionsSection.flowConditionalSummary": "If {{condition}}",
  "functionsSection.flowBodyLoopTitle": "Loop body",
  "functionsSection.flowBodyTitle": "Body (if true)",
  "functionsSection.flowElseBodyTitle": "Else (optional)",

  // show menu step
  "functionsSection.showMenuLabel": "Show menu",
  "functionsSection.showMenuDescription": "Shows a menu with options to choose from; each option calls another function.",
  "functionsSection.showMenuSummary": 'Menu "{{title}}" ({{count}} options)',
  "functionsSection.showMenuTitleLabel": "Menu title",
  "functionsSection.showMenuTitlePlaceholder": "e.g. Quick actions",
  "functionsSection.showMenuItemsLabel": "Options",
  "functionsSection.showMenuEmptyItems": "No options added yet.",
  "functionsSection.showMenuAddItem": "Add option",
  "functionsSection.showMenuNewItemTitle": "New option",
  "functionsSection.showMenuEditItemTitle": "Edit option",
  "functionsSection.showMenuItemLabelLabel": "Option text",
  "functionsSection.showMenuItemLabelPlaceholder": "e.g. Open settings",

  // create gui step
  "functionsSection.createGuiLabel": "Create Gui",
  "functionsSection.createGuiDescription": "Creates and shows a window (Gui) as a global variable, so it can be closed from any function.",
  "functionsSection.createGuiSummary": 'Create Gui "{{title}}" ({{name}})',
  "functionsSection.createGuiTitleLabel": "Window title",
  "functionsSection.createGuiTitlePlaceholder": "e.g. Settings",
  "functionsSection.createGuiVarNamePreview": "Variable: {{name}}",
  "functionsSection.createGuiResizable": "Resizable",
  "functionsSection.createGuiAlwaysOnTop": "Always on top",
  "functionsSection.createGuiNoCaption": "No title bar",
  "functionsSection.createGuiUseColor": "Use a custom background color",
  "functionsSection.createGuiToolWindow": "Tool window (hidden from the taskbar and alt+tab)",
  "functionsSection.createGuiInitialStateLabel": "Initial state",
  "functionsSection.createGuiStateNormal": "Normal",
  "functionsSection.createGuiStateMaximized": "Maximized",
  "functionsSection.createGuiStateMinimized": "Minimized",
  "functionsSection.createGuiWidthLabel": "Width",
  "functionsSection.createGuiHeightLabel": "Height",
  "functionsSection.createGuiXLabel": "X position",
  "functionsSection.createGuiYLabel": "Y position",
  "functionsSection.createGuiAutoPlaceholder": "Automatic",
  "functionsSection.createGuiUseOpacity": "Use custom opacity",
  "functionsSection.createGuiControlsLabel": "Items",
  "functionsSection.createGuiEmptyControls": "No items added yet.",
  "functionsSection.createGuiAddControl": "Add item",
  "functionsSection.createGuiNewControlTitle": "New item",
  "functionsSection.createGuiEditControlTitle": "Edit item",
  "functionsSection.createGuiControlTypeLabel": "Item type",
  "functionsSection.guiControlTypeText": "Text",
  "functionsSection.guiControlTypeButton": "Button",
  "functionsSection.guiControlTypeEdit": "Text box",
  "functionsSection.guiControlTypeCheckbox": "Checkbox",
  "functionsSection.guiControlTypeDropdown": "Dropdown list",
  "functionsSection.guiControlTextLabel": "Text",
  "functionsSection.guiControlTextPlaceholder": "e.g. Confirm",
  "functionsSection.guiControlLabelLabel": "Checkbox text",
  "functionsSection.guiControlInitialValueLabel": "Initial value",
  "functionsSection.guiControlMultiline": "Multiple lines",
  "functionsSection.guiControlCheckedByDefault": "Checked by default",
  "functionsSection.guiControlOptionsLabel": "List options",
  "functionsSection.guiControlTextSummary": 'Text "{{text}}"',
  "functionsSection.guiControlButtonSummary": 'Button "{{text}}" → {{target}}',
  "functionsSection.guiControlEditSummary": "Text box",
  "functionsSection.guiControlCheckboxSummary": 'Checkbox "{{label}}"',
  "functionsSection.guiControlDropdownSummary": "Dropdown list ({{count}} options)",
  "functionsSection.guiControlUseColor": "Use a custom text color",

  // close gui step
  "functionsSection.closeGuiLabel": "Close Gui",
  "functionsSection.closeGuiDescription": "Closes a Gui created by an earlier \"Create Gui\" step.",
  "functionsSection.closeGuiSummary": "Close Gui {{name}}",
  "functionsSection.closeGuiTargetLabel": "Gui to close",
  "functionsSection.closeGuiSelectPlaceholder": "Select a Gui",
  "functionsSection.closeGuiNoneAvailable": 'No Gui available — create a "Create Gui" step first.',
  "functionsSection.conditionKindLabel": "Condition type",
  "functionsSection.conditionKindVariable": "Compare a variable",
  "functionsSection.conditionKindCode": "Raw code",
  "functionsSection.conditionTargetLabel": "Variable",
  "functionsSection.conditionOperatorLabel": "Operator",
  "functionsSection.conditionValueLabel": "Compare to",
  "functionsSection.conditionCodeLabel": "Condition (AHK code)",
  "functionsSection.conditionCodePlaceholder": "e.g. A_Index < 10",
  "functionsSection.conditionGroupBasic": "Basic",

  // condition picker groups
  "functionCategories.mouseConditions": "Mouse",
  "functionCategories.windowConditions": "Windows",
  "functionCategories.systemConditions": "System",

  // function picker (popup)
  "functionPicker.searchPlaceholder": "Search for a function...",
  "functionPicker.noResults": "No functions found.",

  // function categories
  "functionCategories.input": "Basic input",
  "functionCategories.window": "Windows",
  "functionCategories.system": "System",
  "functionCategories.ui": "Interface",
  "functionCategories.flow": "Flow control",

  // step args fields (form)
  "stepArgsFields.fixedValue": "Fixed value",
  "stepArgsFields.fromHeaderParam": "From parameter: {{name}}",
  "stepArgsFields.usingHeaderParam": 'Using the header parameter "{{name}}"',
  "stepArgsFields.usingLocalVariable": 'Using the local variable "{{name}}"',
  "stepArgsFields.usingGlobalVariable": 'Using the global variable "{{name}}"',
  "stepArgsFields.groupHeaderParams": "Header parameters",
  "stepArgsFields.groupLocalVariables": "Local variables",
  "stepArgsFields.groupGlobalVariables": "Global variables",

  // params fields (form)
  "paramsFields.title": "Parameters for {{name}}",
  "paramsFields.capture": "Capture cursor position",
  "paramsFields.capturingDesktop": "Move the mouse and press F8...",
  "paramsFields.capturingBrowser": "Click anywhere on the page...",
  "paramsFields.helpDesktopWindow":
    "Click the target window to focus it, then move the mouse to the desired spot inside it and press F8 — the coordinate will be relative to that window.",
  "paramsFields.helpDesktopScreen":
    "Move the mouse to the desired spot, anywhere on the screen, and press F8 to capture.",
  "paramsFields.helpBrowser":
    "Only works by clicking inside this browser window — it's not possible to capture the cursor position outside it.",
  "paramsFields.capturedAt": "Captured at: {{label}}",
  "paramsFields.activeWindowFallback": "active window",
  "paramsFields.captureFallbackFullScreen":
    "couldn't detect the active window; used the whole screen instead",

  // key combo picker
  "keyCombo.noModifiers": "No modifiers",
  "keyCombo.pressingKey": "Press a key...",
  "keyCombo.placeholder": "Click and press the key",

  // functions.keyPress
  "functions.keyPress.name": "KeyPress",
  "functions.keyPress.description": "Sends a key combination (modifier + key).",
  "functions.keyPress.params.combo.label": "Key",
  "functions.keyPress.params.duration.label": "Hold duration (ms, optional — leave empty for a normal tap)",

  // functions.write
  "functions.write.name": "Write",
  "functions.write.description": "Types a predefined text automatically.",
  "functions.write.params.text.label": "Text",

  // functions.click
  "functions.click.name": "Click",
  "functions.click.description": "Performs a (single or double) mouse click at a coordinate.",
  "functions.click.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",
  "functions.click.params.button.label": "Button",
  "functions.click.params.button.options.Left": "Left",
  "functions.click.params.button.options.Right": "Right",
  "functions.click.params.button.options.Middle": "Middle",
  "functions.click.params.doubleClick.label": "Double click",
  "functions.click.coordinates.x": "Coordinate",

  // functions.open
  "functions.open.name": "Open",
  "functions.open.description": "Opens a program, file, or link.",
  "functions.open.params.path.label": "Path or link",

  // functions.wait
  "functions.wait.name": "Wait",
  "functions.wait.description":
    "Waits a set amount of time (in milliseconds) before continuing.",
  "functions.wait.params.ms.label": "Time (ms)",

  // functions.activateWindow
  "functions.activateWindow.name": "Activate Window",
  "functions.activateWindow.description":
    "Activates (focuses) a window by title, optionally excluding windows containing specific text.",
  "functions.activateWindow.params.title.label": "Window title",
  "functions.activateWindow.params.excludeTitle.label": "Text the window must NOT contain",

  // functions.showMessage
  "functions.showMessage.name": "Show Message",
  "functions.showMessage.description": "Shows a popup with text on screen.",
  "functions.showMessage.params.text.label": "Text",

  // functions.manageWindow
  "functions.manageWindow.name": "Manage Window",
  "functions.manageWindow.description":
    "Minimizes, maximizes, closes, or snaps a window (by title or the active window) to screen halves/corners/center.",
  "functions.manageWindow.params.useActiveWindow.label": "Use the active window (ignores the title)",
  "functions.manageWindow.params.title.label": "Window title",
  "functions.manageWindow.params.excludeTitle.label": "Text the window must NOT contain",
  "functions.manageWindow.params.action.label": "Action",
  "functions.manageWindow.params.action.options.Minimize": "Minimize",
  "functions.manageWindow.params.action.options.Maximize": "Maximize",
  "functions.manageWindow.params.action.options.Close": "Close",
  "functions.manageWindow.params.action.options.Center": "Center",
  "functions.manageWindow.params.action.options.LeftHalf": "Left half of the screen",
  "functions.manageWindow.params.action.options.RightHalf": "Right half of the screen",
  "functions.manageWindow.params.action.options.TopHalf": "Top half of the screen",
  "functions.manageWindow.params.action.options.BottomHalf": "Bottom half of the screen",
  "functions.manageWindow.params.action.options.TopLeft": "Top-left corner",
  "functions.manageWindow.params.action.options.TopRight": "Top-right corner",
  "functions.manageWindow.params.action.options.BottomLeft": "Bottom-left corner",
  "functions.manageWindow.params.action.options.BottomRight": "Bottom-right corner",

  // functions.toggleAlwaysOnTop
  "functions.toggleAlwaysOnTop.name": "Toggle Always On Top",
  "functions.toggleAlwaysOnTop.description":
    "Enables or disables 'always on top' mode for a window by title, or the active window.",
  "functions.toggleAlwaysOnTop.params.useActiveWindow.label":
    "Use the active window (ignores the title)",
  "functions.toggleAlwaysOnTop.params.title.label": "Window title",
  "functions.toggleAlwaysOnTop.params.excludeTitle.label": "Text the window must NOT contain",

  // functions.moveMouse
  "functions.moveMouse.name": "Move Mouse",
  "functions.moveMouse.description": "Moves the mouse cursor to a coordinate, without clicking.",
  "functions.moveMouse.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",
  "functions.moveMouse.coordinates.x": "Coordinate",

  // functions.scroll
  "functions.scroll.name": "Scroll",
  "functions.scroll.description": "Scrolls the mouse wheel up or down.",
  "functions.scroll.params.direction.label": "Direction",
  "functions.scroll.params.direction.options.Up": "Up",
  "functions.scroll.params.direction.options.Down": "Down",
  "functions.scroll.params.amount.label": "Number of wheel notches",

  // functions.drag
  "functions.drag.name": "Drag",
  "functions.drag.description": "Drags the mouse from one coordinate to another (click, move, release).",
  "functions.drag.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",
  "functions.drag.coordinates.x": "Start coordinate",
  "functions.drag.coordinates.endX": "End coordinate",

  // functions.systemAction
  "functions.systemAction.name": "System Action",
  "functions.systemAction.description":
    "Locks the screen, logs off, shuts down, restarts, hibernates, or suspends the computer.",
  "functions.systemAction.params.action.label": "Action",
  "functions.systemAction.params.action.options.Lock": "Lock screen",
  "functions.systemAction.params.action.options.Logoff": "Log off",
  "functions.systemAction.params.action.options.Shutdown": "Shut down",
  "functions.systemAction.params.action.options.Restart": "Restart",
  "functions.systemAction.params.action.options.Hibernate": "Hibernate",
  "functions.systemAction.params.action.options.Sleep": "Sleep",
  "functions.systemAction.params.force.label":
    "Force (closes programs without saving; ignored for Lock/Hibernate/Sleep)",

  // functions.media
  "functions.media.name": "Media/Volume",
  "functions.media.description":
    "Controls volume and media playback (increase, mute, play/pause, next track, etc).",
  "functions.media.params.action.label": "Action",
  "functions.media.params.action.options.VolumeUp": "Increase volume",
  "functions.media.params.action.options.VolumeDown": "Decrease volume",
  "functions.media.params.action.options.Mute": "Mute (toggle)",
  "functions.media.params.action.options.SetVolume": "Set exact volume",
  "functions.media.params.action.options.PlayPause": "Play/Pause",
  "functions.media.params.action.options.Next": "Next track",
  "functions.media.params.action.options.Previous": "Previous track",
  "functions.media.params.action.options.Stop": "Stop",
  "functions.media.params.volume.label": "Exact volume in % (used only in 'Set exact volume')",

  // functions.tooltip
  "functions.tooltip.name": "Tooltip",
  "functions.tooltip.description": "Shows a temporary floating text on screen, near the cursor.",
  "functions.tooltip.params.text.label": "Text",
  "functions.tooltip.params.duration.label":
    "Time until it hides (ms, optional — leave empty to keep it until the next step)",

  // functions.trayTip
  "functions.trayTip.name": "Notification",
  "functions.trayTip.description": "Shows a Windows notification (balloon near the system tray).",
  "functions.trayTip.params.title.label": "Title",
  "functions.trayTip.params.text.label": "Text",

  // functions.beep
  "functions.beep.name": "Beep",
  "functions.beep.description": "Plays a short beep as audible feedback.",
  "functions.beep.params.frequency.label": "Frequency (Hz, optional — default 523)",
  "functions.beep.params.duration.label": "Duration (ms, optional — default 150)",

  // functions.condActiveWindow
  "functions.condActiveWindow.name": "Active window contains",
  "functions.condActiveWindow.description": "Checks whether the active window's title contains a text.",
  "functions.condActiveWindow.params.titleContains.label": "Text the title must contain",

  // functions.condWindowExists
  "functions.condWindowExists.name": "Window exists",
  "functions.condWindowExists.description": "Checks whether a window with the given title exists.",
  "functions.condWindowExists.params.title.label": "Window title",

  // functions.condWindowState
  "functions.condWindowState.name": "Window state",
  "functions.condWindowState.description": "Checks whether a window is maximized, minimized, or normal.",
  "functions.condWindowState.params.title.label": "Window title (empty = active window)",
  "functions.condWindowState.params.state.label": "State",
  "functions.condWindowState.params.state.options.maximized": "Maximized",
  "functions.condWindowState.params.state.options.minimized": "Minimized",
  "functions.condWindowState.params.state.options.normal": "Normal",

  // functions.condKeyState
  "functions.condKeyState.name": "Key pressed",
  "functions.condKeyState.description": "Checks whether a key is currently pressed.",
  "functions.condKeyState.params.key.label": "Key name (e.g. a, Enter, LButton)",

  // functions.condToggleKeyState
  "functions.condToggleKeyState.name": "Toggle key active",
  "functions.condToggleKeyState.description": "Checks whether CapsLock, NumLock, or ScrollLock is on.",
  "functions.condToggleKeyState.params.key.label": "Key",

  // functions.condMousePosition
  "functions.condMousePosition.name": "Mouse position",
  "functions.condMousePosition.description": "Checks whether the mouse cursor is at a specific coordinate.",
  "functions.condMousePosition.params.x.label": "X",
  "functions.condMousePosition.params.y.label": "Y",
  "functions.condMousePosition.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",

  // functions.condPixelColor
  "functions.condPixelColor.name": "Pixel color",
  "functions.condPixelColor.description": "Checks whether a screen pixel has a specific color.",
  "functions.condPixelColor.params.x.label": "X",
  "functions.condPixelColor.params.y.label": "Y",
  "functions.condPixelColor.params.color.label": "Color (e.g. 0xFF0000)",

  // functions.condClipboard
  "functions.condClipboard.name": "Clipboard contains",
  "functions.condClipboard.description": "Checks whether the clipboard contents contain a text.",
  "functions.condClipboard.params.text.label": "Text it must contain",

  // functions.condIdleTime
  "functions.condIdleTime.name": "Idle time",
  "functions.condIdleTime.description": "Checks how long the mouse/keyboard have been idle.",
  "functions.condIdleTime.params.ms.label": "Time (ms)",
  "functions.condIdleTime.params.comparison.label": "Comparison",
  "functions.condIdleTime.params.comparison.options.>": "Greater than",
  "functions.condIdleTime.params.comparison.options.<": "Less than",

  // functions.condTimeOfDay
  "functions.condTimeOfDay.name": "Time of day",
  "functions.condTimeOfDay.description":
    "Checks whether the current time falls within a range (e.g. 09:00 to 18:00).",
  "functions.condTimeOfDay.params.from.label": "From (HH:mm)",
  "functions.condTimeOfDay.params.to.label": "To (HH:mm)",

  // functions.condVolume
  "functions.condVolume.name": "System volume",
  "functions.condVolume.description": "Compares the current system volume (0 to 100) with a value.",
  "functions.condVolume.params.comparison.label": "Comparison",
  "functions.condVolume.params.comparison.options.=": "Equal to",
  "functions.condVolume.params.comparison.options.>": "Greater than",
  "functions.condVolume.params.comparison.options.<": "Less than",
  "functions.condVolume.params.value.label": "Value (0-100)",
};
