/**
 * English strings only. Portuguese needs no dictionary — every call site's
 * fallback argument IS the Portuguese copy, so pt is "free" and always complete.
 * Missing English keys simply fall back to the Portuguese text.
 */
export const en: Record<string, string> = {
  // common
  "common.yes": "Yes",
  "common.no": "No",
  "common.select": "Select",
  "common.optionalSuffix": " (optional)",

  // dashboard / topbar
  "dashboard.save": "Save",
  "dashboard.saveTooltip":
    "Saves to the current file (or asks where, if there isn't one yet) and reloads the script — useful while testing",
  "dashboard.saveAs": "Save As",
  "dashboard.saveAsTooltip": "Asks for a new location to save and reloads the script",
  "dashboard.loadTooltip": "Loads a .ahk script generated by this app",
  "dashboard.tabRemappings": "Remappings",
  "dashboard.tabFunctions": "Functions",
  "dashboard.desktopOnlySave": "Saving is only available in the desktop app.",
  "dashboard.desktopOnlyLoad": "Loading is only available in the desktop app.",
  "dashboard.savedAndReloaded": "Script saved and reloaded at {{path}}",
  "dashboard.savedButRunError": "Saved, but there was an error running it: {{error}}",
  "dashboard.saveError": "Error saving: {{error}}",
  "dashboard.loadError": "Error loading: {{error}}",
  "dashboard.loadedFrom": "Script loaded from {{path}}",
  "dashboard.outOfSpecExtension":
    "File doesn't match the expected format, can't load it (must be a .ahk file).",
  "dashboard.outOfSpec": "File doesn't match the expected format, can't load it: {{error}}.",
  "dashboard.untitledTitle": "new script.ahk*",

  // remappings section
  "remappings.sectionTitle": "Remappings",
  "remappings.addRemapping": "Add new",
  "remappings.newTitle": "New remapping",
  "remappings.editTitle": "Edit remapping",
  "remappings.sourceKey": "Source key",
  "remappings.destKey": "Destination key",
  "remappings.destFunction": "Destination function",
  "remappings.tabKey": "Key",
  "remappings.tabKeyTooltip": "Simple remapping, key to key (1 to 1)",
  "remappings.tabFunction": "Function",
  "remappings.tabFunctionTooltip":
    "Complex remapping: runs a function with multiple steps, conditionals, etc.",
  "remappings.selectFunction": "Select a function",
  "remappings.groupDefault": "Default",
  "remappings.groupCustom": "Custom",
  "remappings.cancel": "Cancel",
  "remappings.save": "Save",
  "remappings.add": "Add",
  "remappings.emptyList": "No remappings yet.",
  "remappings.edit": "Edit",
  "remappings.remove": "Remove",
  "remappings.params": "Parameters",

  // functions section
  "functionsSection.defaultTitle": "Default functions",
  "functionsSection.customTitle": "Custom functions",
  "functionsSection.badgeDefault": "Default",
  "functionsSection.badgeInternal": "Internal use",
  "functionsSection.badgeInternalTooltip":
    "Can't be used directly in a remapping — only makes sense as a step inside another function",
  "functionsSection.nameLabel": "Function name",
  "functionsSection.namePlaceholder": "e.g. OpenNotes",
  "functionsSection.descriptionLabel": "Description",
  "functionsSection.descriptionPlaceholder": "What this function does",
  "functionsSection.add": "Add",
  "functionsSection.emptyCustomList": "No custom functions yet.",
  "functionsSection.remove": "Remove",

  // params fields (form)
  "paramsFields.title": "Parameters for {{name}}",
  "paramsFields.capture": "Capture cursor position",
  "paramsFields.capturingDesktop": "Move the mouse and press F8...",
  "paramsFields.capturingBrowser": "Click anywhere on the page...",
  "paramsFields.helpDesktopWindow":
    "Click the target window to focus it, then move the mouse to the desired spot inside it and press F8 — the coordinate will be relative to that window.",
  "paramsFields.helpDesktopScreen":
    "Move the mouse to the desired spot, anywhere on the screen, and press F8 to capture.",
  "paramsFields.helpBrowser":
    "Only works by clicking inside this browser window — it's not possible to capture the cursor position outside it.",
  "paramsFields.capturedAt": "Captured at: {{label}}",
  "paramsFields.activeWindowFallback": "active window",
  "paramsFields.captureFallbackFullScreen":
    "couldn't detect the active window; used the whole screen instead",

  // key combo picker
  "keyCombo.noModifiers": "No modifiers",
  "keyCombo.pressingKey": "Press a key...",
  "keyCombo.placeholder": "Click and press the key",

  // functions.write
  "functions.write.name": "Write",
  "functions.write.description": "Types a predefined text automatically.",
  "functions.write.params.text.label": "Text",

  // functions.click
  "functions.click.name": "Click",
  "functions.click.description": "Performs a (single or double) mouse click at a coordinate.",
  "functions.click.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",
  "functions.click.params.doubleClick.label": "Double click",
  "functions.click.coordinates.x": "Coordinate",

  // functions.open
  "functions.open.name": "Open",
  "functions.open.description": "Opens a program, file, or link.",
  "functions.open.params.path.label": "Path or link",

  // functions.wait
  "functions.wait.name": "Wait",
  "functions.wait.description":
    "Waits a set amount of time (in milliseconds) before continuing.",
  "functions.wait.params.ms.label": "Time (ms)",

  // functions.activateWindow
  "functions.activateWindow.name": "Activate Window",
  "functions.activateWindow.description":
    "Activates (focuses) a window by title, optionally excluding windows containing specific text.",
  "functions.activateWindow.params.title.label": "Window title",
  "functions.activateWindow.params.excludeTitle.label": "Text the window must NOT contain",

  // functions.showMessage
  "functions.showMessage.name": "Show Message",
  "functions.showMessage.description": "Shows a popup with text on screen.",
  "functions.showMessage.params.text.label": "Text",

  // functions.manageWindow
  "functions.manageWindow.name": "Manage Window",
  "functions.manageWindow.description":
    "Minimizes, maximizes, closes, or snaps a window (by title or the active window) to screen halves/corners/center.",
  "functions.manageWindow.params.useActiveWindow.label": "Use the active window (ignores the title)",
  "functions.manageWindow.params.title.label": "Window title",
  "functions.manageWindow.params.excludeTitle.label": "Text the window must NOT contain",
  "functions.manageWindow.params.action.label": "Action",
  "functions.manageWindow.params.action.options.Minimize": "Minimize",
  "functions.manageWindow.params.action.options.Maximize": "Maximize",
  "functions.manageWindow.params.action.options.Close": "Close",
  "functions.manageWindow.params.action.options.Center": "Center",
  "functions.manageWindow.params.action.options.LeftHalf": "Left half of the screen",
  "functions.manageWindow.params.action.options.RightHalf": "Right half of the screen",
  "functions.manageWindow.params.action.options.TopHalf": "Top half of the screen",
  "functions.manageWindow.params.action.options.BottomHalf": "Bottom half of the screen",
  "functions.manageWindow.params.action.options.TopLeft": "Top-left corner",
  "functions.manageWindow.params.action.options.TopRight": "Top-right corner",
  "functions.manageWindow.params.action.options.BottomLeft": "Bottom-left corner",
  "functions.manageWindow.params.action.options.BottomRight": "Bottom-right corner",

  // functions.toggleAlwaysOnTop
  "functions.toggleAlwaysOnTop.name": "Toggle Always On Top",
  "functions.toggleAlwaysOnTop.description":
    "Enables or disables 'always on top' mode for a window by title, or the active window.",
  "functions.toggleAlwaysOnTop.params.useActiveWindow.label":
    "Use the active window (ignores the title)",
  "functions.toggleAlwaysOnTop.params.title.label": "Window title",
  "functions.toggleAlwaysOnTop.params.excludeTitle.label": "Text the window must NOT contain",

  // functions.moveMouse
  "functions.moveMouse.name": "Move Mouse",
  "functions.moveMouse.description": "Moves the mouse cursor to a coordinate, without clicking.",
  "functions.moveMouse.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",
  "functions.moveMouse.coordinates.x": "Coordinate",

  // functions.scroll
  "functions.scroll.name": "Scroll",
  "functions.scroll.description": "Scrolls the mouse wheel up or down.",
  "functions.scroll.params.direction.label": "Direction",
  "functions.scroll.params.direction.options.Up": "Up",
  "functions.scroll.params.direction.options.Down": "Down",
  "functions.scroll.params.amount.label": "Number of wheel notches",

  // functions.drag
  "functions.drag.name": "Drag",
  "functions.drag.description": "Drags the mouse from one coordinate to another (click, move, release).",
  "functions.drag.params.fullScreen.label":
    "Coordinate relative to the whole screen (otherwise, to the active window)",
  "functions.drag.coordinates.x": "Start coordinate",
  "functions.drag.coordinates.endX": "End coordinate",

  // functions.systemAction
  "functions.systemAction.name": "System Action",
  "functions.systemAction.description":
    "Locks the screen, logs off, shuts down, restarts, hibernates, or suspends the computer.",
  "functions.systemAction.params.action.label": "Action",
  "functions.systemAction.params.action.options.Lock": "Lock screen",
  "functions.systemAction.params.action.options.Logoff": "Log off",
  "functions.systemAction.params.action.options.Shutdown": "Shut down",
  "functions.systemAction.params.action.options.Restart": "Restart",
  "functions.systemAction.params.action.options.Hibernate": "Hibernate",
  "functions.systemAction.params.action.options.Sleep": "Sleep",
  "functions.systemAction.params.force.label":
    "Force (closes programs without saving; ignored for Lock/Hibernate/Sleep)",

  // functions.media
  "functions.media.name": "Media/Volume",
  "functions.media.description":
    "Controls volume and media playback (increase, mute, play/pause, next track, etc).",
  "functions.media.params.action.label": "Action",
  "functions.media.params.action.options.VolumeUp": "Increase volume",
  "functions.media.params.action.options.VolumeDown": "Decrease volume",
  "functions.media.params.action.options.Mute": "Mute (toggle)",
  "functions.media.params.action.options.SetVolume": "Set exact volume",
  "functions.media.params.action.options.PlayPause": "Play/Pause",
  "functions.media.params.action.options.Next": "Next track",
  "functions.media.params.action.options.Previous": "Previous track",
  "functions.media.params.action.options.Stop": "Stop",
  "functions.media.params.volume.label": "Exact volume in % (used only in 'Set exact volume')",
};
